name: Optimize and Deploy Website

on:
  push:
    branches:
      - master # Теперь триггер настроен на ветку master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Скачиваем код из ветки master
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Сжимаем HTML, CSS и JS файлы
      - name: Minify Assets
        uses: nmarus/minify-action@v1
        with:
          source: './'
          output: './'

      # 3. Оптимизируем SVG иконки
      - name: Optimize SVG Icons
        uses: cdgriffith/svgo-action@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # 4. Деплоим сжатую версию в ветку gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages