name: Update Calendar Data
on:
  schedule:
    - cron: '0 * * * *' # Обновлять каждый час
  workflow_dispatch: # Позволяет запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Calendar
        run: |
          curl -s "https://calendar.google.com/calendar/ical/81d94c0e97baf81fbf0e24dd54fb90c6a559ccca45ba65b2242572a864290a42%40group.calendar.google.com/private-d93b1f1a7c77ca3f5d591d38539c7baa/basic.ics" > calendar.ics
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add calendar.ics
          git commit -m "Update calendar data" || exit 0
          git push